### ISSUE TITLE
Tailwind CSS and Alpine.js version of this example

### ISSUE THREAD

**Issue by geoffbeier** [bblanchon/django-htmx-modal-form#4]
Hi,

Thank you very much for your articles and videos. They've been helpful as I've been learning how I like to add HTMX to my toolbox.

I think I've decided that I like the flexibility I get with Tailwind CSS and Alpine.js, and I forked your project to use that stack instead of bootstrap.

I did my work on the "tailwind" branch of [my fork](https://github.com/geoffbeier/django-htmx-modal-form). I thought about offering it back as a PR, but the UI for that on github made it look like accepting the PR would apply it to your bootstrap5 branch.

It would probably be more useful if you wanted to just pull the `tailwind` branch into your repository. Please feel free to do that if you'd like to have a tailwind version next to the others.

Please also feel free to add another part to your articles or videos talking about this stack if you think it's worthwhile. (I have some ambitions of posting about it on my blog, but I've got a bit of a backlog there and may not get to it.)

Thanks again for putting together this demo and the two articles. They've really helped me understand the stack.

**Comment by bblanchon** [comment]
Hi @geoffbeier,

Thank you very much for making this.
I prefer to keep the repositories separated, so I added a link to your fork in the README.

I don't plan on doing any new videos or articles on this topic.
My goal was to introduce the empty response technique, and I think this mission is accomplished.

Best regards,
Benoit

**Comment by geoffbeier** [comment]
> My goal was to introduce the empty response technique, and I think this mission is accomplished.

I'd say so! Thank you.

Best,

Geoff
