### ISSUE TITLE
Bootstrap CSS and Jquery version

### ISSUE THREAD

**Issue by nClarke0101** [bblanchon/django-htmx-modal-form#5]
Hi. 
I love how this looks and works. 
is there anyway you could show me how it could be done with bootstrap and jquery

**Comment by bblanchon** [comment]
Hi @hot202xu1,

By "bootstrap and jquery", I'm assuming you're talking about Bootstrap 4.
Please look at branch "bootstrap4": https://github.com/bblanchon/django-htmx-modal-form/tree/bootstrap4

Best regards,
Benoit
