### ISSUE TITLE
showMessage event more generic

### ISSUE THREAD

**Issue by nerdoc** [bblanchon/django-htmx-modal-form#7]
Hi again, I have another question/idea.
You basically use an `Hx-Trigger` attr to create a custom event, with a payload, and show that payload with `htmx.on()`.

This way, you always have to create the `Hx-Trigger` attr in your view, which is a bit non-djangoish and, despite working, feels like a hack to me. I **really** want to use Django's messaging framework for that, and I recently had an idea, but can't get forther with that. Maybe you know how to.

* First, I would create `<div class="toast"><div id="messages">...</div></div>` tags which contains a typical Django message `{% for ... %}` loop and displays the messages.
* I would create then, as you did, a `Hx-Trigger` attr, just with an empty "showMessage" content
* using CBV, I override the `dispatch()` method (you can do that with a decorator etc in FBV to), so that if any messages are in line, the frontend gets notified:
```python
if messages.get_messages(request):
    response.headers["HX-Trigger"] = "showMessage"
```
* When swapping per HTMX, this triggers your Js part which shows e.g. the `.toast` classes
* the HTMX/HTMX content contains a
```html
<div id="messages">{% for message in messages %}</div>
```

wouldn't this be cleaner?

It should work in theory, but I can't get it to work... Any ideas?

**Comment by bblanchon** [comment]
Hi @nerdoc,

I recently wrote a very simple middleware that converts messages from the messages framework into an `HX-Trigger` header.
I'll try to make a video and a blog post this week.

Best regards,
Benoit

**Comment by nerdoc** [comment]
that would be another, maybe even better solution. I'm eager to see this, because at my first glance it feels a bit strange to add content into `response.header`.

**Comment by bblanchon** [comment]
Here it is: https://www.youtube.com/watch?v=I5_g7XYyemQ

**Comment by nerdoc** [comment]
Thanks, I tried it and it works well, thank you. I just had another idea.
Your approach needs "much" custom Js code to  clone the template and fill it with values using Js.
Wouldn't that be done better using htmx?
1. All the tools like `hx-swap-oob` are included in htmx already
2. Your solution works perfectly when doing a htmx request., bot normal requests don't show these messages.

I thought about a middleware that somehow "adds" HTML-over-the-wire to the request content with a `hx-swap-oob="beforeend" hx-target="toasts"` kind of thing.

I tried it, but I think I am not smart enough to code that ;-)

What do you think about that approach?

**Comment by nerdoc** [comment]
Thanks, I'll comment in the other repo, as my other question belongs there...
